#BASE DE DATOS
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.29:3306/agencia?serverTimezone=UTC
    username: root
    password: admin
#propiedades para que hibernate cree adecuadamente las instrucciones sql
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.29:8761/eureka
  instance:
    instance-id: instancia-vuelos-1
    prefer-ip-address: true
server:
  port: 8003